### ISSUE TITLE
Allow for complex use cases with different metadata

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/BFF#133]
Ensure we handle all these with different metadata flags: XSRF, token forwarding, and 401 response handling.

**Comment by brockallen** [comment]
// @AndersAbel

**Comment by AndersAbel** [comment]
Looks right to me.

The scenario we're looking to support is that server side rendered views are proxied through the BFF. It's usable in a strangler application scenario, where parts of the application are still on server side views while parts are on a SPA. We want to have the server side views (Asp.Net MVC) as a microservice, with the authenticated session owned by the BFF. The views service will accept access tokens. But since it's a normal browser that's the client for these endpoints, we do not want the BFF XSRF, nor the custom 401/challenge handling.

**Comment by oengfer** [comment]
As soon as it is ready, we will be happy to test it.

**Comment by brockallen** [comment]
Yep, working on it this week. We have a release of the ATM library, then this will get updated and one more preview for testing.

**Comment by brockallen** [comment]
PR was merged, so closing.
